### ISSUE TITLE
Contest start time is wrong (possibly because of timezone).

### ISSUE THREAD

**Issue by nobleknightt** [er-knight/contests-web#10]
![IMG_20240603_033506.jpg](https://github.com/er-knight/contests/assets/60701544/1c634f2c-9f0e-4b01-b9d8-7d5868b1219f)

The contest start time is 7:00 PM IST

**Comment by er-knight** [comment]
![IMG_20240603_033506.jpg](https://github.com/er-knight/contests/assets/60701544/bccdc2f8-a108-45cf-bfc6-746a54d1bf62)

**Comment by nobleknightt** [comment]
Possibly resolved by https://github.com/nobleknightt/contestsdb/commit/a658ef03fe48ed013ff4ec589736d6b506b5e697

**Comment by nobleknightt** [comment]
Issue is still there, might be fixed by https://github.com/nobleknightt/contestsdb/commit/3186cc2065e63a2db0a542657473111e0ab7c463
